[build]
  command = "npm run build"

[build.environment]
  NEXT_PRIVATE_STANDALONE = "false"
  SECRETS_SCAN_ENABLED = "false"

[context.production.environment]
  NEXTAUTH_URL = "https://6a30347e765a4e0008910997--dayflow18.netlify.app"

[context.deploy-preview.environment]
  NEXTAUTH_URL = "https://6a30347e765a4e0008910997--dayflow18.netlify.app"

[context.branch-deploy.environment]
  NEXTAUTH_URL = "https://6a30347e765a4e0008910997--dayflow18.netlify.app"

[[headers]]
  for = "/*"
  [headers.values]
    X-DNS-Prefetch-Control = "on"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200
